-- Run in Supabase SQL Editor if you do not use CLI migrations.
create table if not exists public.payables (
  id bigint generated by default as identity primary key,
  title text not null,
  total_due numeric not null check (total_due >= 0),
  amount_paid numeric not null default 0 check (amount_paid >= 0),
  receipt_url text,
  created_at timestamptz default now(),
  constraint amount_not_over_total check (amount_paid <= total_due)
);

alter table public.payables enable row level security;

create policy "Allow all payables for anon"
  on public.payables for all
  using (true)
  with check (true);
