-- Run this entire script in Supabase → SQL Editor → New query → Run.
-- A 404 on /rest/v1/payables means this table has not been created (or API cache is stale).

create table if not exists public.payables (
  id bigint generated by default as identity primary key,
  title text not null,
  total_due numeric not null check (total_due >= 0),
  amount_paid numeric not null default 0 check (amount_paid >= 0),
  receipt_url text,
  created_at timestamptz default now(),
  constraint amount_not_over_total check (amount_paid <= total_due)
);

alter table public.payables enable row level security;

drop policy if exists "Allow all payables for anon" on public.payables;

create policy "Allow all payables for anon"
  on public.payables for all
  using (true)
  with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.payables to anon, authenticated, service_role;
